---
version: 2.1

parameters:
    run_workflow_deploy:
        type: boolean
        default: true

    run_build_arm64_focal:
        type: boolean
        default: true
    run_build_focal_gtk3:
        type: boolean
        default: true

jobs:
    build-arm64-focal:
        machine: true
        environment:
        - OCPN_TARGET=bionic-arm64
        - OCPN_BRANCH=master
        - DOCKER_IMAGE=arm64v8/ubuntu:20.04
        - BUILD_FLAGS=-j3
        - BUILD_ENV=ubuntu
        steps:
        - checkout
        - run: chmod a+x ./ci/*.sh
        - run:
            command: ci/circleci-build-ubuntu-arm64.sh
            no_output_timeout: 30m
        - when:
            condition: <<pipeline.parameters.run_workflow_deploy>>
            steps:
            - run: ci/cloudsmith-upload.sh
    build-focal-gtk3:
        docker:
        - image: circleci/buildpack-deps:focal-scm
        environment:
        - BUILD_GTK3: true
        - OCPN_TARGET: focal-gtk3
        steps:
        - checkout
        - run: >
            echo "deb-src http://us.archive.ubuntu.com/ubuntu/ focal main"
            | sudo tee -a /etc/apt/sources.list
        - run: >
            echo "deb-src http://us.archive.ubuntu.com/ubuntu/ focal-updates main"
            | sudo tee -a /etc/apt/sources.list
        - run: cat /etc/apt/sources.list
        - run: chmod a+x ci/*.sh
        - run: ci/circleci-build-debian.sh
        - when:
            condition: <<pipeline.parameters.run_workflow_deploy>>
            steps:
            - run: ci/cloudsmith-upload.sh
workflows:
    build_1:
        when: <<pipeline.parameters.run_build_arm64_focal>>
        jobs:
        - build-arm64-focal:
            filters:
                branches:
                    ignore:
                    - devel
                    - tmp
                tags:
                    only: /.*/
    build_9:
        when: <<pipeline.parameters.run_build_focal_gtk3>>
        jobs:
        - build-focal-gtk3:
            filters:
                branches:
                    ignore:
                    - devel
                    - tmp
                tags:
                    only: /.*/

